#!/usr/local/bin/php
<?php

define('APP_PATH', __DIR__ . '/application/');
define('APP_NAME', 'demo');

$env = get_cfg_var('IBINGNIAO_TECH_ENV');
if ($env === false) {
    $env = getenv('IBINGNIAO_TECH_ENV');
}
if (!empty($env)) {
    if (strncmp($env, 'prod', 4) != 0) {
        define('APP_DEBUG', true);
    }
    define('APP_STATUS', $env);
}
unset($env);
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/thinkphp/console.php';
